GET http://localhost:8080/balances
Accept: application/json

###

GET http://localhost:8080/open-orders
Accept: application/json

###

GET http://localhost:8080/positions
Accept: application/json

###
